### PR TITLE
That wasn't very B'Op' of me.

### PR DESCRIPTION
**Pull request by tigattack**

### CODE REVIEW

**Comment by BeryJu** [comment]
B'Op.

**Comment by okamidash** [comment]
Please make sure you've read and agreed to:

- [ ] The terms and conditions
- [ ] Birthday Operations Guide (styling)
- [ ] The Void

**Comment by tigattack** [comment]
I agree to nothing. B'Op.

**Comment by okamidash** [comment]
Fantastic, thanks.
:-1:

**Pull request merged**
